src/polls/urls.py
from django.conf.urls import url
from . import views


app_name = 'polls'
urlpatterns = [
    url(r'^favicon.ico$', views.favicon),
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^new/$', views.new, name='new'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
    url(r'^widget/$', views.WidgetView.as_view(), name='widget'),
]

src/website/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
]

src/polls/models.py
import datetime
from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published', default=timezone.now)

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

    def _get_vote_count(self):
        vote_count = self.choices.aggregate(models.Sum('votes'))['votes__sum']
        return vote_count if vote_count is not None else 0

    vote_count = property(_get_vote_count)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='choices')
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

src/polls/forms.py
from django.forms import ModelForm, inlineformset_factory, CharField, TextInput
from .models import Question, Choice


class QuestionForm(ModelForm):
    class Meta:
        model = Question
        fields = ['question_text']
        widgets = {
            'question_text': TextInput(attrs={'class': 'form-control'}),
        }


class ChoiceForm(ModelForm):
    class Meta:
        model = Choice
        fields = ['choice_text']
        widgets = {
            'choice_text': TextInput(attrs={'class': 'form-control'}),
        }


ChoicesFormSet = inlineformset_factory(Question, Choice, fields=('choice_text',), form=ChoiceForm, extra=3, can_delete=False)

src/polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from .models import Choice, Question
from .forms import QuestionForm, ChoicesFormSet


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['question_form'] = QuestionForm()
        context['choices_formset'] = ChoicesFormSet()
        return context


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def favicon(request):
    return HttpResponse()


def new(request):
    if request.method == "POST":
        question_form = QuestionForm(request.POST)
        choices_form_set = ChoicesFormSet(request.POST)
        if question_form.is_valid() and choices_form_set.is_valid():
            question = question_form.save()
            for choice_form in choices_form_set:
                choice = choice_form.save(commit=False)
                choice.question = question
                choice.save()
            return HttpResponseRedirect(reverse('polls:detail', args=(question.id,)))


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choices.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))


class WidgetView(generic.ListView):
    template_name = 'polls/widget.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]

src/polls/templates/polls/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    {% load static %}
    <link rel="stylesheet" href="/static/polls/style.css">
    <title>Polls</title>
</head>
<body>

<div class="container mt-4">
    {% block content %}
    {% endblock %}
</div>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
</body>
</html>

src/polls/templates/polls/detail.html
{% extends "polls/base.html" %}

{% block content %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'polls:index' %}">Polls</a></li>
            <!-- This was an XSS issue as safe is not what you might think-->
            <li class="breadcrumb-item active" aria-current="page">{{ question.question_text }}</li>
        </ol>
    </nav>

    <div class="row mb-3">
        <div class="col">
            <form action="{% url 'polls:vote' question.id %}" method="post">
                {% csrf_token %}
                <div class="list-group mb-3">
                    {% for choice in question.choices.all %}
                        <div class="custom-control custom-radio list-group-item">
                            <input class="custom-control-input" type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                            <label class="custom-control-label" for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
                        </div>
                    {% endfor %}
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary" value="Vote">Submit</button>
                </div>
            </form>
        </div>
    </div>

    <div class="row">
        <div class="col">
            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        </div>
    </div>
{% endblock %}

src/polls/templates/polls/index.html
{% extends "polls/base.html" %}

{% block content %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item active" aria-current="page">Polls</li>
        </ol>
    </nav>

    <div class="row mb-3">
        <div class="col">
            {% if latest_question_list %}
                <div class="list-group">
                    {% for question in latest_question_list %}
                        <a href="{% url 'polls:detail' question.id %}"
                           class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
                            <!-- This is an XSS issue as safe is not what you might think-->
                            <span>{{ question.question_text | safe }}</span>
                            <span class="badge badge-secondary">{{ question.vote_count }} votes</span>
                        </a>
                    {% endfor %}
                </div>
            {% else %}
                <div class="list-group">
                    <div class="list-group-item">No polls are available.</div>
                </div>
            {% endif %}
        </div>
    </div>

    {% include "polls/new.html" %}
{% endblock %}

src/polls/templates/polls/new.html
<div class="row">
    <div class="col">
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#newQModal">New Question</button>
    </div>
</div>

<div class="modal fade" id="newQModal" tabindex="-1" role="dialog" aria-labelledby="newQModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <form action="{% url 'polls:new' %}" method="post">
            {% csrf_token %}
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="newQModalLabel">New Question</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label for="{{ question_form.question_text.id_for_label }}">{{ question_form.question_text.label }}</label>
                        {{ question_form.question_text }}
                    </div>
                    {{ choices_formset.management_form }}
                    {% for form in choices_formset %}
                        {{ form.id }}
                        <div class="form-group">
                            <label for="{{ form.choice_text.id_for_label }}">{{ form.choice_text.label }}</label>
                            {{ form.choice_text }}
                        </div>
                    {% endfor %}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save Question</button>
                </div>
            </div>
        </form>
    </div>
</div>

src/polls/templates/polls/results.html
{% extends "polls/base.html" %}

{% block content %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'polls:index' %}">Polls</a></li>
            <li class="breadcrumb-item"><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
            <li class="breadcrumb-item active" aria-current="page">Results</li>
        </ol>
    </nav>

    <div class="row mb-3">
        <div class="col">
            <ul class="list-group">
            {% for choice in question.choices.all %}
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    <span>{{ choice.choice_text }}</span>
                    <span class="badge badge-secondary">{{ choice.votes }} votes</span>
                </li>
            {% endfor %}
            </ul>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <a href="{% url 'polls:detail' question.id %}" class="btn btn-primary" role="button">Vote Again</a>
        </div>
    </div>
{% endblock %}

src/polls/templates/polls/widget.html
{% extends "polls/base.html" %}

{% block content %}
    <div class="row mb-3">
        <div class="col">
            {% if latest_question_list %}
                <div class="list-group">
                    {% for question in latest_question_list %}
                        <a href="{% url 'polls:detail' question.id %}"
                           class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
                            <!-- This is an XSS issue as safe is not what you might think-->
                            <span>{{ question.question_text | safe }}</span>
                            <span class="badge badge-secondary">{{ question.vote_count }} votes</span>
                        </a>
                    {% endfor %}
                </div>
            {% else %}
                <div class="list-group">
                    <div class="list-group-item">No polls have been created.</div>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}